In [1]:
import pandas as pd

In [2]:
resume_df = pd.read_csv("..//data//processed//resume_processed.csv")
resume_df.head()

,Resume_str,Category,clean_resume_text
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,HR,hr administrator marketing associate hr admin...
1,"HR SPECIALIST, US HR OPERATIONS ...",HR,hr specialist us hr operations summary versat...
2,HR DIRECTOR Summary Over 2...,HR,hr director summary over years experience in ...
3,HR SPECIALIST Summary Dedica...,HR,hr specialist summary dedicated driven and dy...
4,HR MANAGER Skill Highlights ...,HR,hr manager skill highlights hr skills hr depa...

In [10]:
from src.skill_extractor.skill_extractor import extract_skills

In [11]:
resume_df["skills"] = (
    resume_df["clean_resume_text"].apply(extract_skills)
)

resume_df.head()

,Resume_str,Category,clean_resume_text,skills
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,HR,hr administrator marketing associate hr admin...,"[aws, statistics]"
1,"HR SPECIALIST, US HR OPERATIONS ...",HR,hr specialist us hr operations summary versat...,[git]
2,HR DIRECTOR Summary Over 2...,HR,hr director summary over years experience in ...,[excel]
3,HR SPECIALIST Summary Dedica...,HR,hr specialist summary dedicated driven and dy...,[excel]
4,HR MANAGER Skill Highlights ...,HR,hr manager skill highlights hr skills hr depa...,"[aws, excel]"

In [12]:
resume_df.to_csv("..//data//processed//resume_with_skills.csv", index=False)